openapi: 3.0.0
info:
  title: Your Application API
  version: 1.0.0
servers:
- url: /
paths:
  /api/v1/applications:
    get:
      summary: Get a list of applications
      description: Retrieve a list of applications.
      parameters:
      - name: page
        in: query
        description: Page number for pagination.
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: per_page
        in: query
        description: Number of applications per page for pagination.
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
    post:
      summary: Create a new application
      description: Endpoint to create a new application.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1_applications_body'
        required: true
      responses:
        "201":
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
  /api/v1/applications/{app_id}:
    get:
      summary: Get an application by ID
      description: Retrieve an application by its ID.
      parameters:
      - name: app_id
        in: path
        description: ID of the application to retrieve.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
  /api/v1/applications/{app_id}/metrics:
    post:
      summary: Add metrics for an application
      description: Endpoint to add metrics for a specific application.
      parameters:
      - name: app_id
        in: path
        description: ID of the application to which metrics are being added.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/app_id_metrics_body'
        required: true
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
  /api/v1/applications/{app_id}/metrics/{metric_name}:
    get:
      summary: Get metrics for a specific metric of an application
      description: Retrieve metrics for a specific metric of an application.
      parameters:
      - name: app_id
        in: path
        description: ID of the application.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: metric_name
        in: path
        description: Name of the metric.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: duration
        in: query
        description: |
          Duration for which the metrics should be aggregated. Available options are hour, day, week, month, quarter, year. Defaulted to 'hour'.
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: hour
          enum:
          - hour
          - day
          - week
          - month
          - quarter
          - year
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_3'
                x-content-type: application/json
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404_1'
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        records:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: ID of the application.
              name:
                type: string
                description: Name of the application.
              created_at:
                type: string
                description: Timestamp when the application was created.
                format: date-time
              updated_at:
                type: string
                description: Timestamp when the application was last updated.
                format: date-time
            example:
              updated_at: 2000-01-23T04:56:07.000+00:00
              name: name
              created_at: 2000-01-23T04:56:07.000+00:00
              id: id
        meta:
          type: object
          properties:
            page:
              type: integer
              description: Current page number.
            items:
              type: integer
              description: Number of items in the current page.
            count:
              type: string
              description: Total count of applications.
          example:
            count: count
            page: 0
            items: 6
      example:
        records:
        - updated_at: 2000-01-23T04:56:07.000+00:00
          name: name
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
        - updated_at: 2000-01-23T04:56:07.000+00:00
          name: name
          created_at: 2000-01-23T04:56:07.000+00:00
          id: id
        meta:
          count: count
          page: 0
          items: 6
    apiv1applications_application:
      type: object
      properties:
        name:
          type: string
          description: Name of the application.
    v1_applications_body:
      required:
      - name
      type: object
      properties:
        application:
          $ref: '#/components/schemas/apiv1applications_application'
    inline_response_201:
      type: object
      properties:
        id:
          type: string
          description: ID of the created application.
        name:
          type: string
          description: Name of the created application.
        created_at:
          type: string
          description: Timestamp when the application was created.
          format: date-time
        updated_at:
          type: string
          description: Timestamp when the application was last updated.
          format: date-time
      example:
        updated_at: 2000-01-23T04:56:07.000+00:00
        name: name
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
    inline_response_400:
      type: object
      properties:
        message:
          type: string
          example: Invalid request payload.
    inline_response_200_1:
      type: object
      properties:
        id:
          type: string
          description: ID of the application.
        name:
          type: string
          description: Name of the application.
        created_at:
          type: string
          description: Timestamp when the application was created.
          format: date-time
        updated_at:
          type: string
          description: Timestamp when the application was last updated.
          format: date-time
      example:
        updated_at: 2000-01-23T04:56:07.000+00:00
        name: name
        created_at: 2000-01-23T04:56:07.000+00:00
        id: id
    inline_response_404:
      type: object
      properties:
        message:
          type: string
          example: Application not found.
    apiv1applicationsapp_idmetrics_metrics:
      type: object
      properties:
        name:
          type: string
          description: Name of the metric.
        value:
          type: number
          description: Value of the metric.
        timestamp:
          type: integer
          description: Unix timestamp of when the metric was recorded.
          format: int64
    app_id_metrics_body:
      type: object
      properties:
        metrics:
          type: array
          items:
            $ref: '#/components/schemas/apiv1applicationsapp_idmetrics_metrics'
      example:
        metrics:
        - name: metric1
          value: 10
          timestamp: 1111
    inline_response_200_2:
      type: object
      properties:
        message:
          type: string
          example: Metric(s) added successfully.
      example:
        message: Metric(s) added successfully.
    inline_response_200_3:
      type: object
      properties:
        date:
          type: string
          description: Date of the metric.
          format: date-time
          example: 2024-05-06T00:00:00Z
        count:
          type: integer
          description: Count of the metric.
          example: 3
        p99:
          type: number
          description: 99th percentile of the metric.
          example: 30
        p95:
          type: number
          description: 95th percentile of the metric.
          example: 30
        p50:
          type: number
          description: 50th percentile of the metric.
          example: 5
        avg:
          type: number
          description: Average value of the metric.
          example: 12.666666666666666
      example:
        date: 2024-05-06T00:00:00Z
        p99: 30
        avg: 12.666666666666666
        count: 3
        p50: 5
        p95: 30
    inline_response_404_1:
      type: object
      properties:
        message:
          type: string
          example: Application or metric not found.
